version: '3'

services:
  app:
    build: .
    command: gunicorn -w 4 --threads 2 -b 0.0.0.0:8000 main:app
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
